# Generated by Django 6.0.5 on 2026-05-30 15:16

import django.db.models.deletion
import positions.fields
from django.db import migrations, models

import hagrid.products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("position", positions.fields.PositionField(default=-1)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("position", positions.fields.PositionField(default=-1)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, unique=True)),
                ("position", positions.fields.PositionField(default=-1)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="SizeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("position", positions.fields.PositionField(default=-1)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dashboard_is_public",
                    models.BooleanField(
                        default=True, help_text="Show the dashboard to anonymous users"
                    ),
                ),
                (
                    "gallery_is_public",
                    models.BooleanField(
                        default=True, help_text="Show the gallery to anonymous users"
                    ),
                ),
                (
                    "reservations_enabled",
                    models.BooleanField(
                        default=False, help_text="Allow people to submit reservations"
                    ),
                ),
                (
                    "reservations_link_in_navbar",
                    models.BooleanField(
                        default=False,
                        help_text="Show the link to the reservation form in the navbar",
                    ),
                ),
                (
                    "login_link_in_navbar",
                    models.BooleanField(
                        default=True, help_text="Show the link to the login page in the navbar"
                    ),
                ),
                (
                    "dashboard_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML that will be rendered on the top of the dashboard",
                    ),
                ),
                (
                    "reservation_faq_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML that will be rendered reservation detail pages",
                    ),
                ),
                (
                    "counting_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Allow people with 'secret' URLs for counting items to record changes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", positions.fields.PositionField(default=-1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="operations.event",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valid_at",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_prices",
                        to="operations.event",
                    ),
                ),
                (
                    "valid_for_products_from_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historic_prices",
                        to="operations.event",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesignVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="products.design",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_variations",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="CountAccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=hagrid.products.models.generate_access_code,
                        help_text="unique URL part, keep this (rather) secret",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A name to identify or describe this code to admins (only shown there)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        help_text="disable the code so it cannot be used at the moment"
                    ),
                ),
                (
                    "as_queue",
                    models.BooleanField(default=False, help_text="use queue mode for this code"),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only products from these events",
                        to="operations.event",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only variations these products",
                        to="products.product",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only variations these sizes",
                        to="products.size",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="size",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="products.sizescale",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.sizescale",
            ),
        ),
        migrations.CreateModel(
            name="SizeVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                ("count_reserved_until", models.DateTimeField(blank=True, null=True)),
                ("count_disabled_until", models.DateTimeField(blank=True, null=True)),
                ("count_disabled_reason", models.CharField(blank=True, max_length=30, null=True)),
                ("count_prio_bumped", models.BooleanField(default=False)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("few available", "few available"),
                            ("sold out", "sold out"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "amount_ordered",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Amount ordered from the producer"
                    ),
                ),
                (
                    "amount_received",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Amount received from the producer"
                    ),
                ),
                (
                    "amount_preordered",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Amount preordered from customers"
                    ),
                ),
                (
                    "crate_size",
                    models.IntegerField(
                        blank=True,
                        help_text="How many items of this variation come in a crate?",
                        null=True,
                    ),
                ),
                (
                    "design_variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_variations",
                        to="products.designvariation",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="products.size",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("name", models.TextField(blank=True, default="")),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_events",
                        to="products.sizevariation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailabilityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("few available", "few available"),
                            ("sold out", "sold out"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("few available", "few available"),
                            ("sold out", "sold out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="products.sizevariation",
                    ),
                ),
            ],
        ),
    ]
