# Generated by Django 6.0.5 on 2026-05-31 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_remove_openstatus_selling_items_from_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sizevariation",
            old_name="amount_received",
            new_name="amount_initial",
        ),
        migrations.RemoveField(
            model_name="sizevariation",
            name="amount_ordered",
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("product", "valid_for_products_from_event", "valid_at")},
        ),
    ]
