# Generated by Django 6.0.5 on 2026-06-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_amount_received_sizevariation_amount_initial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countaccesscode",
            name="sizes",
        ),
        migrations.RemoveField(
            model_name="countevent",
            name="name",
        ),
        migrations.AlterField(
            model_name="availabilityevent",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_events",
                to="products.sizevariation",
            ),
        ),
    ]
