# Generated by Django 6.0.5 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_countaccesscode_sizes_remove_countevent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countaccesscode",
            name="allow_automatic_availability",
            field=models.BooleanField(
                default=True,
                help_text="use automatic determination of availability based on counts as default in the forms",
            ),
        ),
    ]
