# Generated by Django 2.2.4 on 2019-11-13 18:34

import positions.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20191113_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="position",
            field=positions.fields.PositionField(default=None),
        ),
        migrations.AlterField(
            model_name="size",
            name="position",
            field=positions.fields.PositionField(default=None),
        ),
        migrations.AlterField(
            model_name="sizegroup",
            name="position",
            field=positions.fields.PositionField(default=None),
        ),
    ]
