# Generated by Django 3.0 on 2019-12-08 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_auto_20191113_2221"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabilityevent",
            name="user",
        ),
    ]
