# Generated by Django 4.2.16 on 2024-11-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_variation_count_and_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="counting_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow people with 'secret' URLs for counting items to record changes",
            ),
        ),
    ]
