# Generated by Django 2.2.4 on 2019-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_auto_20190829_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
