# Generated by Django 2.2.4 on 2019-12-07 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_auto_20191113_2301"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="action_secret",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
