# Generated by Django 3.0 on 2019-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_packing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='packing_mode',
            field=models.CharField(choices=[('aggregated', "Don't seperate reservation parts"), ('seperated parts', 'Pack every reservation part individually')], default='aggregated', max_length=20),
        ),
    ]
