# Generated by Django 6.0.5 on 2026-05-30 15:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("day_1", models.DateField()),
                ("last_day", models.DateField()),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-day_1"],
            },
        ),
        migrations.CreateModel(
            name="OpenStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="information about this operating time", null=True
                    ),
                ),
                (
                    "public_info",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="shown on dashboard",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("open", "Open"),
                            ("presale", "Presale pickup"),
                        ],
                        default="closed",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "open statuses",
                "ordering": ["datetime"],
            },
        ),
    ]
