# Generated by Django 6.0.5 on 2026-05-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openstatus",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_statuses",
                to="operations.event",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openstatus",
            name="selling_items_from",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_at",
                to="operations.event",
            ),
            preserve_default=False,
        ),
    ]
