# Generated by Django 6.0.5 on 2026-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_openstatus_event_openstatus_selling_items_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openstatus",
            name="selling_items_from",
        ),
        migrations.AddField(
            model_name="openstatus",
            name="selling_items_from",
            field=models.ManyToManyField(blank=True, related_name="sold_at", to="operations.event"),
        ),
    ]
