# Generated by Django 6.0.5 on 2026-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_remove_openstatus_selling_items_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openstatus",
            name="allow_reservations_from",
            field=models.ManyToManyField(
                blank=True, related_name="reservation_at", to="operations.event"
            ),
        ),
    ]
