# Generated by Django 2.2.4 on 2019-09-04 19:49

from django.db import migrations, models


def create_singleton(apps, schema_editor):
    StoreSettings = apps.get_model("products", "StoreSettings")
    db_alias = schema_editor.connection.alias
    StoreSettings.objects.using(db_alias).bulk_create(
        [
            StoreSettings(),
        ]
    )


def remove_singleton(apps, schema_editor):
    from django.db import models

    StoreSettings = apps.get_model("products", "StoreSettings")
    db_alias = schema_editor.connection.alias
    models.Model.delete(StoreSettings.objects.using(db_alias).get(id=1))


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial_squashed_0004_auto_20190828_1153"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_is_public",
                    models.BooleanField(
                        default=True, help_text="Show the dashboard to anonymous users"
                    ),
                ),
                (
                    "gallery_is_public",
                    models.BooleanField(
                        default=True, help_text="Show the gallery to anonymous users"
                    ),
                ),
                (
                    "reservations_enabled",
                    models.BooleanField(
                        default=False, help_text="Allow people to submit reservations"
                    ),
                ),
                (
                    "reservations_link_in_navbar",
                    models.BooleanField(
                        default=False,
                        help_text="Show the link to the reservation form in the navbar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
        migrations.RunPython(create_singleton, remove_singleton),
    ]
