# Generated by Django 3.0 on 2019-12-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_availabilityevent_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailabilityEvent',
            new_name='VariationAvailabilityEvent',
        ),
    ]
