# Generated by Django 4.2.16 on 2024-11-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_id_alter_size_id_alter_sizegroup_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="products.product",
            ),
        ),
    ]
