# Generated by Django 4.2.16 on 2024-11-25 09:09

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_alter_variation_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML that will be rendered in the dashboard section",
                    ),
                ),
                ("position", positions.fields.PositionField(default=-1)),
                ("display_in_dashboard", models.BooleanField(help_text="Show the group in the dashboard", default=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.productgroup",
            ),
        ),
    ]
