# Generated by Django 4.2.16 on 2024-11-29 00:00

from django.db import migrations, models
import django.db.models.deletion
import hagrid.products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_productgroup_remove_product_previous_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="counted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VariationCountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("name", models.TextField(blank=True, default="")),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_events",
                        to="products.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationCountAccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=hagrid.products.models.generate_access_code,
                        help_text="unique URL part, keep this (rather) secret",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        help_text="disable the code so it cannot be used at the moment"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only variations these products",
                        to="products.product",
                    ),
                ),
                (
                    "sizegroups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only variations these sizegroups",
                        to="products.sizegroup",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="allow editing only variations these sizes",
                        to="products.size",
                    ),
                ),
            ],
        ),
    ]
