# Generated by Django 4.2.16 on 2024-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_storesettings_counting_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="count_reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
