# Generated by Django 4.2.16 on 2024-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_variation_count_reserved_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="variationcountaccesscode",
            name="as_queue",
            field=models.BooleanField(
                default=False, help_text="use queue mode for this code"
            ),
        ),
    ]
