# Generated by Django 4.2.16 on 2024-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_variationcountaccesscode_as_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="count_prio_bumped",
            field=models.BooleanField(default=False),
        ),
    ]
