# Generated by Django 4.2.16 on 2024-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_variation_count_prio_bumped"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="crate_size",
            field=models.IntegerField(
                blank=True,
                help_text="How many items of this product come in a crate?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="crate_size",
            field=models.IntegerField(
                blank=True,
                help_text="How many items of this variation come in a crate (overrides product setting)?",
                null=True,
            ),
        ),
    ]
