# Generated by Django 4.2.16 on 2024-12-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_product_crate_size_variation_crate_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="count_disabled_reason",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="count_disabled_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
