# Generated by Django 5.1.15 on 2025-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_productgroup_offer_in_reservations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
