# Generated by Django 5.1.15 on 2025-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('few available', 'few available'), ('sold out', 'sold out')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='variationavailabilityevent',
            name='new_state',
            field=models.CharField(choices=[('available', 'available'), ('few available', 'few available'), ('sold out', 'sold out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variationavailabilityevent',
            name='old_state',
            field=models.CharField(choices=[('available', 'available'), ('few available', 'few available'), ('sold out', 'sold out')], max_length=20),
        ),
    ]
