# Generated by Django 4.2.4 on 2023-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_auto_20191226_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="alt_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
