# Generated by Django 5.1.15 on 2025-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_galleryimage_variation_galleryimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
