# Generated by Django 6.0.5 on 2026-05-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="galleryimages/")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("caption", models.TextField(blank=True)),
                ("alt_text", models.TextField(blank=True)),
                (
                    "design_variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.designvariation",
                    ),
                ),
            ],
        ),
    ]
