# Generated by Django 6.0.5 on 2026-06-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        ("products", "0003_remove_countaccesscode_sizes_remove_countevent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="design_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="products.designvariation",
            ),
        ),
    ]
