# Generated by Django 4.2.16 on 2024-11-29 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "open",
                    models.BooleanField(
                        default=False, help_text="whether we're open or closed"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="information about this operating time",
                        null=True,
                    ),
                ),
                (
                    "public_info",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="shown on dashboard",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
