# Generated by Django 4.2.16 on 2024-11-29 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openstatus",
            options={"ordering": ["datetime"], "verbose_name_plural": "open statuses"},
        ),
    ]
