# Generated by Django 5.1.15 on 2025-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_openstatus_open_openstatus_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openstatus',
            name='public_info',
            field=models.CharField(blank=True, default=None, help_text='shown on dashboard', max_length=1000, null=True),
        ),
    ]
