"""
Django settings for hagrid project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import datetime
import os
from email.utils import getaddresses
from pathlib import Path

import environ
from django.contrib.messages import constants as messages

# PACKAGE_DIR is the directory containing this settings.py file, which is usually src/hagrid
PACKAGE_DIR = os.path.dirname(os.path.abspath(__file__))
# REPO_DIR defaults to the directory containing the src folder
REPO_DIR = os.path.dirname(os.path.dirname(PACKAGE_DIR))

env = environ.Env()
# for syntax see https://django-environ.readthedocs.io/en/latest/
# read env file from ENV_PATH or fall back to a .env file in the project root
env_path = env.str("ENV_PATH", default=os.path.join(REPO_DIR, ".env"))
print(f"Loading hagrid environment from {Path(env_path).absolute()}")
environ.Env.read_env(env_file=env_path)

DEBUG = env.bool("DEBUG")

DATA_DIR = env.str("DATA_DIR", os.path.join(REPO_DIR, "data"))
PUBLIC_DIR = env.str("PUBLIC_DIR", os.path.join(DATA_DIR, "public"))
STATIC_ROOT = env.str("STATIC_ROOT", os.path.join(PUBLIC_DIR, "static"))

PRIVATE_DIR = env.str("PRIVATE_DIR", os.path.join(DATA_DIR, "private"))
LOG_DIR = env.str("LOG_DIR", os.path.join(PRIVATE_DIR, "logs"))
MEDIA_ROOT = env.str("MEDIA_ROOT", os.path.join(PRIVATE_DIR, "media"))

DIRECTORIES = {
    "DATA_DIR": DATA_DIR,
    "PUBLIC_DIR": PUBLIC_DIR,
    "STATIC_ROOT": STATIC_ROOT,
    "PRIVATE_DIR": PRIVATE_DIR,
    "LOG_DIR": LOG_DIR,
    "MEDIA_ROOT": MEDIA_ROOT,
}
for directory in DIRECTORIES.values():
    os.makedirs(directory, exist_ok=True)

if "SECRET_KEY" in env:
    SECRET_KEY = env.str("SECRET_KEY")
else:
    from hagrid.utils import django_secret_from_file

    SECRET_FILE = os.path.join(PRIVATE_DIR, ".secret")
    SECRET_KEY = django_secret_from_file(SECRET_FILE)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

SITE_URL = env.str("SITE_URL").rstrip("/")

EMAIL_CONFIG = env.email_url("EMAIL_URL")
vars().update(EMAIL_CONFIG)
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env.str("SERVER_EMAIL")
ADMINS = getaddresses([env("ADMINS")])

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# Application definition
INSTALLED_APPS = [
    "daphne",
    "compressor",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_eventstream",
    "django_htmx",
    "rest_framework",
    "hagrid.products",
    "hagrid.reservations",
    "hagrid.gallery",
    "hagrid.api",
    "hagrid.operations",
    "hagrid.staticpages",
]

LOGIN_URL = "admin:login"

MESSAGE_TAGS = {
    messages.DEBUG: "alert alert-dark",
    messages.INFO: "alert alert-info",
    messages.SUCCESS: "alert alert-success",
    messages.WARNING: "alert alert-warning",
    messages.ERROR: "alert alert-danger",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "hagrid.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "hagrid.products.context.contextprocessor",
                "hagrid.staticpages.context.context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "hagrid.wsgi.application"
ASGI_APPLICATION = "hagrid.asgi.application"

# SASS compiling
COMPRESS_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {"default": env.db_url()}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {"DEFAULT_PERMISSION_CLASSES": ["hagrid.api.permissions.IsSafeMethodOnly"]}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"
USE_I18N = False
USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(PACKAGE_DIR, "static"),)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"default": {"format": "[%(levelname)s] %(asctime)s %(name)s :: %(message)s"}},
    "filters": {
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "default",
            "filters": ["require_debug_true"],
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "file": {
            "level": "DEBUG",
            "formatter": "default",
            "filters": [],
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "ephios.log"),
            "when": "midnight",
            "backupCount": env.int("LOGGING_BACKUP_DAYS", default=14),
            "atTime": datetime.time(4),
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "ephios": {
            "handlers": ["mail_admins", "console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django": {"handlers": [], "level": "INFO", "propagate": True},
        "django.server": {"handlers": [], "level": "INFO", "propagate": True},
    },
    "root": {"handlers": ["mail_admins", "console", "file"], "level": "INFO"},
}

ENABLE_DEBUG_TOOLBAR = env.bool("DEBUG_TOOLBAR", False)
if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("django_extensions")
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = env.list("INTERNAL_IPS", default=["127.0.0.1"])
