# Generated by Django 6.0.5 on 2026-05-30 15:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("team_name", models.CharField(max_length=30)),
                ("contact_name", models.CharField(max_length=30)),
                ("contact_mail", models.EmailField(blank=True, max_length=254)),
                ("contact_dect", models.CharField(blank=True, max_length=10)),
                ("secret", models.CharField(max_length=16, unique=True)),
                ("action_secret", models.UUIDField(default=uuid.uuid4)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("editable", "editable"),
                            ("submitted", "submitted"),
                            ("packed", "packed"),
                            ("ready for pickup", "ready to be picked up"),
                            ("picked up", "picked up"),
                            ("canceled", "cancelled"),
                        ],
                        default="unapproved",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "packing_mode",
                    models.CharField(
                        choices=[
                            ("aggregated", "Don't seperate reservation parts"),
                            ("seperated parts", "Pack every reservation part individually"),
                        ],
                        default="aggregated",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_state",
                    models.CharField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("editable", "editable"),
                            ("submitted", "submitted"),
                            ("packed", "packed"),
                            ("ready for pickup", "ready to be picked up"),
                            ("picked up", "picked up"),
                            ("canceled", "cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("unapproved", "unapproved"),
                            ("editable", "editable"),
                            ("submitted", "submitted"),
                            ("packed", "packed"),
                            ("ready for pickup", "ready to be picked up"),
                            ("picked up", "picked up"),
                            ("canceled", "cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.PositiveSmallIntegerField(default=0)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="reservations.reservationpart",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_positions",
                        to="products.sizevariation",
                    ),
                ),
            ],
        ),
    ]
