# Generated by Django 6.0.5 on 2026-06-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_openstatus_allow_reservations_from"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="operations.event",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("unapproved", "unapproved"),
                    ("editable", "editable"),
                    ("submitted", "submitted"),
                    ("packing", "packing"),
                    ("packed", "packed"),
                    ("ready for pickup", "ready to be picked up"),
                    ("picked up", "picked up"),
                    ("canceled", "cancelled"),
                ],
                default="unapproved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservationevent",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("unapproved", "unapproved"),
                    ("editable", "editable"),
                    ("submitted", "submitted"),
                    ("packing", "packing"),
                    ("packed", "packed"),
                    ("ready for pickup", "ready to be picked up"),
                    ("picked up", "picked up"),
                    ("canceled", "cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservationevent",
            name="old_state",
            field=models.CharField(
                choices=[
                    ("unapproved", "unapproved"),
                    ("editable", "editable"),
                    ("submitted", "submitted"),
                    ("packing", "packing"),
                    ("packed", "packed"),
                    ("ready for pickup", "ready to be picked up"),
                    ("picked up", "picked up"),
                    ("canceled", "cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
