# Generated by Django 2.2.4 on 2019-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_reservation_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
